/**
 * File Description: Command-line interface for producing, directing, designing, reviewing, and rendering Aideos films.
 * Inputs and outputs: CLI arguments and subcommands -> runs production pipeline, review, or inspection commands.
 * Used by: bin/aideos, npm run backend (entry point).
 */

import { Command, Option } from "commander";
import fs from "fs/promises";
import path from "path";
import { execSync } from "child_process";
import dotenv from "dotenv";
import type { Film } from "../src/dl/schema";
import { produceAudioPipeline, buildFilmFromAudioResult } from "./audio";
import { createEngine } from "./engine";
import { runProduction } from "./pipeline/run";
import { runDirector } from "./pipeline/director";
import type { ProductionFormat, ProductionProgress, ProductionStage } from "./pipeline/types";
import type { TtsBackendName } from "./tts";
import { registerAllCheckCommands, rewriteAllCheckArgv } from "./allCheck/cli";

dotenv.config({ quiet: true });

/** Resolved from the module, not the shell, so the CLI works from any cwd. */
const ROOT = path.resolve(__dirname, "..");
const GENERATED_PATH = path.join(ROOT, "src/dl/films/generated.ts");
const ACTIVE_FILM_PATH = path.join(ROOT, "src/dl/activeFilm.ts");

const program = new Command();
program
  .name("aideos-backend")
  .description("Generate and render Aideos films from natural language")
  .version("1.0.0");



const FORMATS = {
  long: { script: "render", label: "long (1920×1080) → out/long.mp4" },
  reel: { script: "render:reel", label: "reel (1080×1920) → out/reel.mp4" },
} as const;

/** Keeps the hand-written explanation that makes this file readable. */
const activeFilmModule = () =>
  `import { generatedFilm } from "./films/generated";
import type { Film } from "./schema";

/**
 * Which film renders. One line, so swapping the subject of the whole pipeline
 * is a one-word change rather than a search through the components.
 */
export const ACTIVE_FILM: Film = generatedFilm;
`;

/**
 * Written from the *parsed* film, so the defaults the schema applies are on the
 * page. The raw tool arguments omit them, and a module annotated `Film` that
 * leaves out `w`, `dashed` or `stage` typechecks only by accident.
 */
const generatedModule = (film: Film) =>
  `import type { Film } from "../schema";

/**
 * Generated by \`npm run backend -- produce\`. Regenerating overwrites it.
 *
 * Pure data - the only import is a type, so the validator can load this in
 * plain Node with no React, no fonts and no browser.
 */
export const generatedFilm: Film = ${JSON.stringify(film, null, 2)};
`;

import { runPreRenderSyncGate } from "./ideation/segmentSync";

program
  .command("produce")
  .description("Produce an audio-first Aideos film from a narration script")
  .requiredOption("--script <script>", "Narration script text")
  .option("--out <dir>", "Output directory for generated files", "public")
  .option("--music <src>", "Optional background music audio file in public/")
  .option("--sfx", "Automatically place transition sound effects at segment boundaries")
  .addOption(
    new Option("--format <format>", "which composition to render")
      .choices(["long", "reel", "both", "none"])
      .default("none"),
  )
  .action(
    async (options: {
      script: string;
      out: string;
      music?: string;
      sfx?: boolean;
      format: "long" | "reel" | "both" | "none";
    }) => {
      if (!options.script || options.script.trim().length === 0) {
        throw new Error("A shot with no narration is not allowed mid-script in v1");
      }

      const outDir = path.resolve(ROOT, options.out);
      console.log(`[Audio-First Pipeline] Synthesizing script into audio timing spine...`);

      const audioResult = await produceAudioPipeline(options.script, outDir);
      console.log(
        `[Audio-First Pipeline] Concatenated ${audioResult.segments.length} segment(s) into voiceover.wav (${audioResult.totalAudioDuration.toFixed(2)}s total duration)`,
      );

      // Build transition SFX track if requested
      const sfxTrack = options.sfx
        ? audioResult.segments.slice(1).map((seg, idx) => ({
            timeSec: Number(seg.startOffset.toFixed(3)),
            src: "transition.wav",
            volume: 0.8,
          }))
        : undefined;

      const musicTrack = options.music
        ? { src: options.music, volume: 0.8, duckUnderVoiceover: true }
        : undefined;

      const title = options.script.slice(0, 30).trim() || "Produced Film";
      const film = buildFilmFromAudioResult(title, audioResult, {
        music: musicTrack,
        sfx: sfxTrack,
      });

      console.log(`[Phase 3 - Semantic Sync] Running pre-render sync gate...`);
      const syncResult = await runPreRenderSyncGate(film, audioResult.segments);

      console.log(`[Sync Gate Verdicts]`);
      syncResult.verdicts.forEach((v: any, idx: number) => {
        console.log(
          `  Shot ${v.shotId} (Segment ${idx + 1}): [${v.status.toUpperCase()}] narration="${v.segmentText.slice(0, 35)}..." -> visualDirection="${v.visualDirection.slice(0, 45)}..."`,
        );
      });

      // Save segment->shot mapping artifact
      const mappingArtifactPath = path.join(outDir, "segment_shot_mapping.json");
      await fs.writeFile(
        mappingArtifactPath,
        JSON.stringify(syncResult.segmentShotMappings, null, 2),
        "utf-8",
      );
      console.log(`Saved segment->shot mapping artifact to ${mappingArtifactPath}`);

      const filmJsonPath = path.join(outDir, "film.json");
      await fs.writeFile(filmJsonPath, JSON.stringify(film, null, 2), "utf-8");
      console.log(`Saved film JSON to ${filmJsonPath}`);

      await fs.writeFile(GENERATED_PATH, generatedModule(film), "utf-8");
      console.log(`Saved generated film to ${GENERATED_PATH}`);

      const previousActive = await fs.readFile(ACTIVE_FILM_PATH, "utf-8").catch(() => null);
      await fs.writeFile(ACTIVE_FILM_PATH, activeFilmModule(), "utf-8");
      console.log(`Updated activeFilm.ts to use generatedFilm.`);

      console.log(`Validating...`);
      try {
        execSync("npm run validate", { stdio: "inherit", cwd: ROOT });
        console.log(`Validation successful.`);
      } catch {
        if (previousActive !== null) {
          await fs.writeFile(ACTIVE_FILM_PATH, previousActive, "utf-8");
        }
        throw new Error("Validation failed.");
      }

      if (options.format !== "none") {
        const formats =
          options.format === "both" ? (["long", "reel"] as const) : ([options.format] as const);
        for (const key of formats) {
          console.log(`Rendering ${FORMATS[key].label}...`);
          try {
            execSync(`npm run ${FORMATS[key].script}`, { stdio: "inherit", cwd: ROOT });
          } catch {
            throw new Error(`Render failed for the ${key} format.`);
          }
        }
        console.log(`Render complete.`);
      }
    },
  );

/** Renders a progress event as one readable CLI line. */
function formatProgress(event: ProductionProgress): string {
  const seconds = (event.elapsedMs / 1000).toFixed(0).padStart(4);
  const pct = event.progress !== undefined ? ` ${Math.round(event.progress * 100)}%` : "";
  return `[${seconds}s] ${event.stage.padEnd(9)} ${event.status.padEnd(8)}${pct} ${event.message}`;
}

program
  .command("film")
  .description(
    "One call from a script to finished, verified mp4s: narration, design, GPU b-roll, render, review",
  )
  .option("--script <text>", "narration script or Claude screenplay as a literal string")
  .option("--script-file <path>", "path to a screenplay markdown file")
  .option("--title <title>", "film title; also the source of the package slug")
  .option("--slug <slug>", "package slug under videos/ (lowercase letters, digits, dashes)")
  .option("--formats <list>", "comma-separated formats to render", "long,reel")
  .option("--out <dir>", "where the finished mp4s land", "out")
  .option("--broll", "generate b-roll footage on the GPU and wire it into the film")
  .option("--broll-engine <name>", "which VideoEngine renders b-roll", "ssh-wangp")
  .option("--broll-clips <n>", "maximum number of b-roll clips", "4")
  .option("--broll-seconds <n>", "length of each b-roll clip in seconds", "8")
  .option("--tts <backend>", "pin the speech synthesizer (kokoro, google, say, tone)")
  .option("--voice <voice>", "voice id for the chosen synthesizer")
  .option("--speed <n>", "narration pace multiplier; below 1 slows delivery", "1")
  .option("--music <src>", "background music filename inside public/")
  .option("--no-resume", "ignore cached stage results and run everything again")
  .option("--force <stages>", "comma-separated stages to re-run even when resuming")
  .option("--stop-after <stage>", "stop cleanly after this stage")
  .option("--skip-verify", "skip the closing frame and audio inspection pass")
  .option("--no-bespoke", "keep the template design instead of designing the film with the agent or server model")
  .option("--design-timeout <minutes>", "how long to wait for the connected agent's design", "20")
  .action(
    async (options: {
      script?: string;
      scriptFile?: string;
      title?: string;
      slug?: string;
      formats: string;
      out: string;
      broll?: boolean;
      brollEngine: string;
      brollClips: string;
      brollSeconds: string;
      tts?: TtsBackendName;
      voice?: string;
      speed: string;
      music?: string;
      resume: boolean;
      force?: string;
      stopAfter?: ProductionStage;
      skipVerify?: boolean;
        bespoke?: boolean;
        designTimeout: string;
    }) => {
      const script = options.scriptFile
        ? await fs.readFile(path.resolve(ROOT, options.scriptFile), "utf-8")
        : options.script;
      if (!script) throw new Error("pass either --script or --script-file");

      const title =
        options.title ??
        script.match(/^#\s+(.+)$/m)?.[1]?.trim() ??
        "Untitled Aideos Film";

      const result = await runProduction(
        {
          script,
          title,
          slug: options.slug,
          formats: options.formats.split(",").map((f) => f.trim()).filter(Boolean) as ProductionFormat[],
          outDir: options.out,
          broll: Boolean(options.broll),
          brollEngine: options.brollEngine,
          brollMaxClips: Number(options.brollClips),
          brollSeconds: Number(options.brollSeconds),
          ttsBackend: options.tts,
          voice: options.voice,
          speed: Number(options.speed),
          music: options.music,
          resume: options.resume,
          force: options.force?.split(",").map((s) => s.trim()) as ProductionStage[] | undefined,
          stopAfter: options.stopAfter,
          skipVerify: options.skipVerify,
          bespoke: options.bespoke,
          designAgentTimeoutMs: Number(options.designTimeout) * 60_000,
        },
        (event) => console.log(formatProgress(event)),
      );

      console.log(`\n${result.title} (${result.slug})`);
      console.log(`  ${result.shotCount} shots · ${result.durationSec.toFixed(2)}s · narrated by ${result.ttsBackend}`);
      console.log(`  film manifest: ${path.relative(ROOT, result.filmPath)}`);
      for (const clip of result.brollClips) {
        console.log(`  b-roll ${clip.shotId}: ${path.relative(ROOT, clip.path)} (${clip.durationSec.toFixed(2)}s)`);
      }
      for (const output of result.outputs) {
        console.log(
          `  ${output.format}: ${path.relative(ROOT, output.path)} ` +
            `(${output.width}x${output.height}, ${output.durationSec.toFixed(2)}s, ` +
            `${(output.sizeBytes / 1024 / 1024).toFixed(1)} MB)`,
        );
      }
      if (result.warnings.length > 0) {
        console.log(`\n  ${result.warnings.length} warning(s):`);
        for (const warning of result.warnings) console.log(`    - ${warning}`);
      }
      if (result.stoppedAfter) console.log(`\n  stopped after the ${result.stoppedAfter} stage, as requested`);
    },
  );

program
  .command("direct")
  .description(
    "Auto-prompt: an LLM director drafts a screenplay from your prompt, then produces it end to end",
  )
  .argument("<prompt>", "what the film should explain, as plain language")
  .option("--title <title>", "film title; overrides the one the director drafts for itself")
  .option("--slug <slug>", "package slug under videos/ (lowercase letters, digits, dashes)")
  .option("--formats <list>", "comma-separated formats to render", "long,reel")
  .option("--out <dir>", "where the finished mp4s land", "out")
  .option("--broll", "generate b-roll footage on the GPU and wire it into the film")
  .option("--broll-engine <name>", "which VideoEngine renders b-roll", "ssh-wangp")
  .option("--broll-clips <n>", "maximum number of b-roll clips", "4")
  .option("--broll-seconds <n>", "length of each b-roll clip in seconds", "8")
  .option("--tts <backend>", "pin the speech synthesizer (kokoro, google, say, tone)")
  .option("--voice <voice>", "voice id for the chosen synthesizer")
  .option("--speed <n>", "narration pace multiplier; below 1 slows delivery", "1")
  .option("--music <src>", "background music filename inside public/")
  .option("--max-attempts <n>", "how many screenplay drafts the director may attempt", "3")
  .option("--no-resume", "ignore cached stage results and run everything again")
  .option("--force <stages>", "comma-separated stages to re-run even when resuming")
  .option("--stop-after <stage>", "stop cleanly after this stage")
  .option("--skip-verify", "skip the closing frame and audio inspection pass")
  .option("--no-bespoke", "keep the template design instead of designing the film with the agent or server model")
  .option("--design-timeout <minutes>", "how long to wait for the connected agent's design", "20")
  .action(
    async (
      prompt: string,
      options: {
        title?: string;
        slug?: string;
        formats: string;
        out: string;
        broll?: boolean;
        brollEngine: string;
        brollClips: string;
        brollSeconds: string;
        tts?: TtsBackendName;
        voice?: string;
        speed: string;
        music?: string;
        maxAttempts: string;
        resume: boolean;
        force?: string;
        stopAfter?: ProductionStage;
        skipVerify?: boolean;
        bespoke?: boolean;
        designTimeout: string;
      },
    ) => {
      const result = await runDirector(
        {
          prompt,
          title: options.title,
          slug: options.slug,
          formats: options.formats.split(",").map((f) => f.trim()).filter(Boolean) as ProductionFormat[],
          outDir: options.out,
          broll: Boolean(options.broll),
          brollEngine: options.brollEngine,
          brollMaxClips: Number(options.brollClips),
          brollSeconds: Number(options.brollSeconds),
          ttsBackend: options.tts,
          voice: options.voice,
          speed: Number(options.speed),
          music: options.music,
          maxAttempts: Number(options.maxAttempts),
          resume: options.resume,
          force: options.force?.split(",").map((s) => s.trim()) as ProductionStage[] | undefined,
          stopAfter: options.stopAfter,
          skipVerify: options.skipVerify,
          bespoke: options.bespoke,
          designAgentTimeoutMs: Number(options.designTimeout) * 60_000,
        },
        (event) => console.log(formatProgress(event)),
      );

      console.log(`\n${result.title} (${result.slug})`);
      console.log(
        `  drafted in ${result.draftAttempts} attempt(s) · ${result.shotCount} shots · ` +
          `${result.durationSec.toFixed(2)}s · narrated by ${result.ttsBackend}`,
      );
      console.log(`  screenplay: ${path.relative(ROOT, result.scriptPath)}`);
      console.log(`  film manifest: ${path.relative(ROOT, result.filmPath)}`);
      for (const clip of result.brollClips) {
        console.log(`  b-roll ${clip.shotId}: ${path.relative(ROOT, clip.path)} (${clip.durationSec.toFixed(2)}s)`);
      }
      for (const output of result.outputs) {
        console.log(
          `  ${output.format}: ${path.relative(ROOT, output.path)} ` +
            `(${output.width}x${output.height}, ${output.durationSec.toFixed(2)}s, ` +
            `${(output.sizeBytes / 1024 / 1024).toFixed(1)} MB)`,
        );
      }
      if (result.warnings.length > 0) {
        console.log(`\n  ${result.warnings.length} warning(s):`);
        for (const warning of result.warnings) console.log(`    - ${warning}`);
      }
      if (result.stoppedAfter) console.log(`\n  stopped after the ${result.stoppedAfter} stage, as requested`);
    },
  );

program
  .command("mcp")
  .description("Serve the production pipeline as an MCP server over stdio")
  .action(async () => {
    const { startMcpServer } = await import("./mcp/server");
    await startMcpServer();
  });

program
  .command("engine-test")
  .description("Render one clip through a VideoEngine (smoke test for the GPU render loop)")
  .argument("<prompt>", "Text-to-video prompt for the clip")
  .option("--engine <name>", "which engine to drive", "null")
  .option("--seconds <seconds>", "clip duration in seconds", "5")
  .option("--seed <seed>", "optional integer seed")
  .option("--out <dir>", "where to write the fetched clip", "out/gpu-test")
  .action(
    async (prompt: string, options: { engine: string; seconds: string; seed?: string; out: string }) => {
      const engine = createEngine(options.engine);
      const spec = {
        prompt,
        seconds: Number(options.seconds),
        width: 832,
        height: 480,
        fps: 16,
        ...(options.seed !== undefined ? { seed: Number(options.seed) } : {}),
        modelProfile: "small" as const,
      };
      console.log(`[${engine.name}] submitting job: "${prompt}"`);
      const handle = await engine.submit(spec);
      console.log(`[${engine.name}] job ${handle.jobId} submitted; polling status...`);
      // Poll until terminal state. Renders run under tmux remotely, so a dropped
      // local process never kills the GPU work; re-running resumes at poll stage.
      for (;;) {
        await new Promise((r) => setTimeout(r, 15000));
        const st = await engine.status(handle.jobId);
        const pct = st.progress !== undefined ? ` (${Math.round(st.progress * 100)}%)` : "";
        console.log(`[${engine.name}] ${st.state}${pct}`);
        if (st.state === "failed") throw new Error(st.error || "job failed");
        if (st.state === "done") break;
      }
      const dest = path.join(ROOT, options.out, `${handle.jobId}.mp4`);
      await engine.fetchOutput(handle.jobId, dest);
      console.log(`[${engine.name}] clip saved to ${dest}`);
    },
  );

program
  .command("design-brief")
  .description("Write videos/<film>/design/BRIEF.md: everything a designer needs to design the film")
  .argument("<film>", "film id under videos/")
  .action(async (film: string) => {
    const { writeDesignBrief } = await import("./designSpec/brief");
    console.log(writeDesignBrief(film));
  });

program
  .command("design-build")
  .description("Compile videos/<film>/design/design.json into the film; writes it only when the design check passes")
  .argument("<film>", "film id under videos/")
  .option("--source <who>", "who made the design: agent, server-model or hand-built", "agent")
  .action(async (film: string, options: { source: string }) => {
    const { buildDesign, formatBuildStatus } = await import("./designSpec/build");
    const source = options.source as "agent" | "server-model" | "hand-built";
    if (!["agent", "server-model", "hand-built"].includes(source)) throw new Error(`unknown --source "${options.source}"`);
    const status = buildDesign(film, source);
    console.log(formatBuildStatus(film, status));
    if (status.state !== "passed") process.exitCode = 1;
  });

program
  .command("design-check")
  .description("Check films against the design standard layer (schema, scene, art, palette, continuity, audio lock, honest data)")
  .argument("[films...]", "film ids under videos/; omit with --all to check every film")
  .option("--all", "check every film under videos/")
  .option("--stills", "also render review stills of each passing film into .frames/<id>/")
  .option("--json", "print the reports as JSON for an agent to consume")
  .action(async (films: string[], options: { all?: boolean; stills?: boolean; json?: boolean }) => {
    const { checkFilmDesignById, formatDesignReport } = await import("./designCheck/designCheck");
    const { readdirSync, existsSync } = await import("node:fs");
    const videosDir = path.join(__dirname, "../videos");
    const ids = options.all ? readdirSync(videosDir).filter((d) => existsSync(path.join(videosDir, d, "film.json"))) : films;
    if (ids.length === 0) throw new Error("name at least one film id, or pass --all");
    const reports = ids.map((id) => checkFilmDesignById(id));
    if (options.json) console.log(JSON.stringify(reports, null, 2));
    else for (const r of reports) console.log(formatDesignReport(r));
    if (options.stills) {
      const { renderFilmReviewStills } = await import("./designCheck/stills");
      for (const r of reports.filter((rep) => rep.ok)) {
        console.log(`[design-check] review stills for ${r.filmId}: ${await renderFilmReviewStills(r.filmId)}`);
      }
    }
    if (reports.some((r) => !r.ok)) process.exitCode = 1;
  });

program
  .command("review")
  .description("Review a rendered video against the good-video rubric: measurable checks on the mp4 (and film data), evidence frames, exit 1 when a gate fails")
  .argument("<target>", "a film slug under videos/ or the path of an mp4")
  .option("--film <film.json>", "film data to read the camera, persistence and geometry from (a slug review finds it itself)")
  .option("--words <file>", "word timings (voiceover_words.json) or narration text, for audio sync, caption matching and grounding")
  .option("--out <dir>", "where review.json and the review/ evidence frames are written")
  .option("--no-ocr", "skip the OCR pass (no caption, readability, overlap or grounding checks)")
  .option("--json", "print the report as JSON on stdout (progress goes to stderr)")
  .action(async (target: string, options: { film?: string; words?: string; out?: string; ocr: boolean; json?: boolean }) => {
    const { reviewVideo, formatReview } = await import("./review/review");
    try {
      const report = await reviewVideo({
        target,
        film: options.film,
        words: options.words,
        outDir: options.out,
        skipOcr: !options.ocr,
        onProgress: (m) => console.error(`[review] ${m}`),
      });
      console.log(options.json ? JSON.stringify(report, null, 2) : formatReview(report));
      if (!report.passed) process.exitCode = 1;
    } catch (err) {
      // A tool error is not a gate failure: exit 2 so callers can tell "could not review" from "reviewed and failed".
      console.error(err instanceof Error ? err.message : String(err));
      process.exitCode = 2;
    }
  });

program
  .command("gemini-review")
  .description("Review a rendered mp4 video or run pairwise comparison using Gemini 3.8 Flash against the 12-criterion quality rubric")
  .argument("<video>", "Path to rendered mp4 video file")
  .option("--pairwise <other>", "Optional second mp4 video to run cross-review pairwise comparison against")
  .option("--film <path>", "Optional path to film.json for camera track and boundary facts")
  .option("--no-facts", "Skip deterministic facts extraction (OCR, audio loudness, ffprobe)")
  .option("--json", "Print output report as raw JSON")
  .action(async (video: string, options: { pairwise?: string; film?: string; facts: boolean; json?: boolean }) => {
    const { reviewVideo, reviewPairwise, formatReviewSummary } = await import("./geminiReview");

    if (options.pairwise) {
      const logMsg = `Starting pairwise review: Video A (${video}) vs Video B (${options.pairwise})...`;
      options.json ? console.error(logMsg) : console.log(logMsg);
      const report = await reviewPairwise(video, options.pairwise, {
        onProgress: (msg) => options.json ? console.error(`  ${msg}`) : console.log(`  ${msg}`),
      });

      if (options.json) {
        console.log(JSON.stringify(report, null, 2));
      } else {
        const formatScore = (n: number) => typeof n === "number" ? n.toFixed(1) : String(n ?? "N/A");
        console.log("");
        console.log("=== PAIRWISE CROSS-REVIEW RESULTS ===");
        console.log(`Video A: ${report.videoA.path}`);
        console.log(`  Rating by its watcher: ${formatScore(report.videoA.ratingByWatcher)}`);
        console.log(`  Rating by other agent: ${formatScore(report.videoA.ratingByOther)}`);
        console.log(`  FINAL SCORE: ${formatScore(report.videoA.finalRating)}`);
        console.log("");
        console.log(`Video B: ${report.videoB.path}`);
        console.log(`  Rating by its watcher: ${formatScore(report.videoB.ratingByWatcher)}`);
        console.log(`  Rating by other agent: ${formatScore(report.videoB.ratingByOther)}`);
        console.log(`  FINAL SCORE: ${formatScore(report.videoB.finalRating)}`);
        console.log("");
        console.log(`WINNER: ${report.winner}`);
      }
      return;
    }

    const logMsg = `Reviewing video with Gemini 3.8 Flash: ${video}...`;
    options.json ? console.error(logMsg) : console.log(logMsg);
    const report = await reviewVideo(video, {
      filmPath: options.film,
      skipFacts: !options.facts,
      onProgress: (msg) => options.json ? console.error(`  ${msg}`) : console.log(`  ${msg}`),
    });

    if (options.json) {
      console.log(JSON.stringify(report, null, 2));
    } else {
      console.log("\n" + formatReviewSummary(report));
    }

    if (report.verdict !== "ACCEPT") {
      process.exitCode = 1;
    }
  });

registerAllCheckCommands(program);

// parseAsync, so a rejected action surfaces as a one-line CLI error rather than
// an unhandled rejection with a raw stack trace, and exits non-zero.
program.parseAsync(rewriteAllCheckArgv(process.argv)).catch((err: unknown) => {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
