import { Command, Option } from "commander";
import OpenAI from "openai";
import fs from "fs/promises";
import path from "path";
import { execSync } from "child_process";
import dotenv from "dotenv";
import { z } from "zod";
import { DEVICE_BLOCKS, filmBaseSchema, parseFilm } from "../src/dl/schema";
import type { Film } from "../src/dl/schema";
import { processAudioForFilm } from "./audio";
import { createEngine } from "./engine";

dotenv.config({ quiet: true });

/** Resolved from the module, not the shell, so the CLI works from any cwd. */
const ROOT = path.resolve(__dirname, "..");
const GENERATED_PATH = path.join(ROOT, "src/dl/films/generated.ts");
const ACTIVE_FILM_PATH = path.join(ROOT, "src/dl/activeFilm.ts");

const program = new Command();
program
  .name("aideos-backend")
  .description("Generate and render Aideos films from natural language")
  .version("1.0.0");

/**
 * The tool schema *is* the film schema. Hand-writing a JSON Schema alongside
 * `filmSchema` means every constraint the validator enforces — id patterns,
 * `dur` bounds, unit-space points, the block union — has to be remembered
 * twice, and the copy silently rots. Deriving it means the model is told about
 * a new field the moment the schema grows one.
 *
 * `io: "input"` so defaulted fields stay optional: the model omitting `zoom`
 * is correct, not a mistake. The pacing rules in `superRefine` cannot be
 * expressed in JSON Schema, so they live in the system prompt below and are
 * enforced for real by `parseFilm` before anything is written to disk.
 */
const filmParameters = z.toJSONSchema(filmBaseSchema, {
  io: "input",
  target: "draft-7",
  unrepresentable: "any",
  reused: "inline",
}) as Record<string, unknown>;

const systemPrompt = `You are an expert at generating Aideos Film configurations. Create a visually engaging explainer video.

Structure:
- Provide realistic 2D coordinates for nodes (e.g. x: 0..2000, y: 0..1000). Lay the graph out left to right so every edge points forward.
- Every node id named by an edge or by a shot's "look" must exist in canvas.nodes. Node and shot ids are lowercase letters, digits and dashes only.
- The first shot must use move: "cut" — it has nothing to move from.
- A shot with move: "cut" opens the next chapter, and the chapter rail reads its label from the chapters array. So the number of shots with move: "cut" must equal chapters.length, and each cut must land where that chapter's section of the argument begins.
- Do not provide 'audio', 'voiceover', or 'captions' fields, nor 'src' for AnalogyInset, as these require specific existing files in the public directory.
- stage: "none" carries no blocks.
- For each shot, provide 'scriptText' containing the narration/script the AI voice should speak during that shot. Keep it conversational.

Pacing (all enforced; a violation fails validation):
- Device blocks are: ${DEVICE_BLOCKS.join(", ")}.
- No shot holding a device may run past 25s, and no device may follow itself — put the canvas or another device between them.
- A text beat (stage: "frame") at least every 60-90s.
- A return to the bare canvas (stage: "none") at least every 60-90s.
- stage: "anchor" and stage: "frame" must carry at least one block.
- stage: "anchor" cannot look at "all" — name the single node the panel grows out of.
- At most 3 accents in one shot. Each device block, each StatCounter, each Card with state "active", each TextReveal with an accentWord and each Math whose text contains *stars* spends one.
- Each shot's dur is 2..45 seconds, and the film totals at least 10s.`;

const FORMATS = {
  long: { script: "render", label: "long (1920×1080) → out/long.mp4" },
  reel: { script: "render:reel", label: "reel (1080×1920) → out/reel.mp4" },
} as const;

/** Keeps the hand-written explanation that makes this file readable. */
const activeFilmModule = () =>
  `import { generatedFilm } from "./films/generated";
import type { Film } from "./schema";

/**
 * Which film renders. One line, so swapping the subject of the whole pipeline
 * is a one-word change rather than a search through the components.
 */
export const ACTIVE_FILM: Film = generatedFilm;
`;

/**
 * Written from the *parsed* film, so the defaults the schema applies are on the
 * page. The raw tool arguments omit them, and a module annotated `Film` that
 * leaves out `w`, `dashed` or `stage` typechecks only by accident.
 */
const generatedModule = (film: Film) =>
  `import type { Film } from "../schema";

/**
 * Generated by \`npm run backend generate\`. Regenerating overwrites it.
 *
 * Pure data — the only import is a type, so the validator can load this in
 * plain Node with no React, no fonts and no browser.
 */
export const generatedFilm: Film = ${JSON.stringify(film, null, 2)};
`;

program
  .command("generate")
  .description("Generate an Aideos film from a prompt")
  .argument("<prompt>", "Natural language description of the video")
  .addOption(
    new Option("--format <format>", "which composition to render")
      .choices(["long", "reel", "both"])
      .default("long"),
  )
  .action(async (prompt: string, options: { format: "long" | "reel" | "both" }) => {
    // Constructed here rather than at module scope so `--help` and `--version`
    // still work without a key, and so a missing one is one line, not a stack.
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) throw new Error("OPENAI_API_KEY is not set. Put it in .env or the environment.");
    const openai = new OpenAI({ apiKey });

    console.log(`Generating film for prompt: "${prompt}"...`);

    const completion = await openai.chat.completions.create({
      model: "gpt-4o-2024-08-06",
      // A film is a large payload; the default ceiling truncates the tool call
      // into unparseable JSON, which reads as a mystery syntax error.
      max_completion_tokens: 16384,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: prompt },
      ],
      tools: [
        {
          type: "function",
          function: {
            name: "generate_aideos_film",
            description:
              "Generates an Aideos Film JSON structure representing canvas nodes, shots, and blocks.",
            parameters: filmParameters,
          },
        },
      ],
      tool_choice: { type: "function", function: { name: "generate_aideos_film" } },
    });

    const choice = completion.choices[0];
    if (!choice) throw new Error("The model returned no choices.");
    if (choice.finish_reason === "length")
      throw new Error("The model's tool call was cut off mid-JSON. Ask for a shorter film.");

    const toolCall = choice.message.tool_calls?.[0];
    if (!toolCall || toolCall.type !== "function")
      throw new Error("The model returned no film tool call.");

    let raw: unknown;
    try {
      raw = JSON.parse(toolCall.function.arguments);
    } catch (err) {
      throw new Error(`The model's tool call was not valid JSON: ${(err as Error).message}`);
    }

    // Validate before touching the tree. `npm run validate` catches the same
    // errors, but only after `activeFilm.ts` has been repointed at the broken
    // film — and then studio, frames and render all fail until it is reverted.
    let film = parseFilm(raw);

    const publicDir = path.join(ROOT, "public");
    if (process.env.DEEPGRAM_API_KEY) {
      console.log("Deepgram key found, generating TTS and STT...");
      try {
        film = await processAudioForFilm(film, publicDir);
      } catch (err) {
        console.error("Audio generation failed, continuing without audio:", err);
      }
    } else {
      console.log("No DEEPGRAM_API_KEY found, skipping audio generation.");
    }

    await fs.writeFile(GENERATED_PATH, generatedModule(film), "utf-8");
    console.log(`Saved generated film to ${GENERATED_PATH}`);

    const previousActive = await fs.readFile(ACTIVE_FILM_PATH, "utf-8").catch(() => null);
    await fs.writeFile(ACTIVE_FILM_PATH, activeFilmModule(), "utf-8");
    console.log(`Updated activeFilm.ts to use generatedFilm.`);

    console.log(`Validating...`);
    try {
      execSync("npm run validate", { stdio: "inherit", cwd: ROOT });
      console.log(`Validation successful.`);
    } catch {
      if (previousActive !== null) {
        await fs.writeFile(ACTIVE_FILM_PATH, previousActive, "utf-8");
        console.error("Restored the previous activeFilm.ts; the generated film is still on disk.");
      }
      throw new Error("Validation failed.");
    }

    const formats =
      options.format === "both" ? (["long", "reel"] as const) : ([options.format] as const);
    for (const key of formats) {
      console.log(`Rendering ${FORMATS[key].label}...`);
      try {
        execSync(`npm run ${FORMATS[key].script}`, { stdio: "inherit", cwd: ROOT });
      } catch {
        throw new Error(`Render failed for the ${key} format.`);
      }
    }
    console.log(`Render complete.`);
  });

program
  .command("engine-test")
  .description("Render one clip through a VideoEngine (smoke test for the GPU render loop)")
  .argument("<prompt>", "Text-to-video prompt for the clip")
  .option("--engine <name>", "which engine to drive", "null")
  .option("--seconds <seconds>", "clip duration in seconds", "5")
  .option("--seed <seed>", "optional integer seed")
  .option("--out <dir>", "where to write the fetched clip", "out/gpu-test")
  .action(
    async (prompt: string, options: { engine: string; seconds: string; seed?: string; out: string }) => {
      const engine = createEngine(options.engine);
      const spec = {
        prompt,
        seconds: Number(options.seconds),
        width: 832,
        height: 480,
        fps: 16,
        ...(options.seed !== undefined ? { seed: Number(options.seed) } : {}),
        modelProfile: "small" as const,
      };
      console.log(`[${engine.name}] submitting job: "${prompt}"`);
      const handle = await engine.submit(spec);
      console.log(`[${engine.name}] job ${handle.jobId} submitted; polling status...`);
      // Poll until terminal state. Renders run under tmux remotely, so a dropped
      // local process never kills the GPU work; re-running resumes at poll stage.
      for (;;) {
        await new Promise((r) => setTimeout(r, 15000));
        const st = await engine.status(handle.jobId);
        const pct = st.progress !== undefined ? ` (${Math.round(st.progress * 100)}%)` : "";
        console.log(`[${engine.name}] ${st.state}${pct}`);
        if (st.state === "failed") throw new Error(st.error || "job failed");
        if (st.state === "done") break;
      }
      const dest = path.join(ROOT, options.out, `${handle.jobId}.mp4`);
      await engine.fetchOutput(handle.jobId, dest);
      console.log(`[${engine.name}] clip saved to ${dest}`);
    },
  );

// parseAsync, so a rejected action surfaces as a one-line CLI error rather than
// an unhandled rejection with a raw stack trace, and exits non-zero.
program.parseAsync().catch((err: unknown) => {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
