import type { Episode } from "../schema";

/**
 * ---------------------------------------------------------------------------
 * EPISODE: KV cache, from zero to "why can't two models share one"
 * ---------------------------------------------------------------------------
 * Adapted from scripts/kvcache.md.
 *
 * Durations are derived from the narration word count of each beat at roughly
 * 145 words per minute, so a voiceover recorded from the source script lands on
 * picture without re-timing. They are estimates, not measurements: once there
 * is a real VO track, re-time from its word timings.
 *
 * Accent convention for this episode:
 *   primary   (cyan)  = the cache, the fix, things that work
 *   secondary (amber) = cost, waste, incompatibility, warnings
 */
export const kvcacheEpisode: Episode = {
  id: "kvcache",
  title: "KV Cache Explained",
  subtitle: "From zero to why two models can't share one",
  fps: 30,
  subject: "cardShelf",
  theme: "circuit",
  endTag: "Keys · Values · Prefill",
  audio: { src: "audio.mp3", trimBefore: 6 },

  scenes: [
    // ---------------------------------------------------------------- PART 0
    {
      id: "cold-open",
      start: 0,
      duration: 11,
      kicker: "KV CACHE",
      headline: "Imagine dictating a novel to a scribe, one word at a time.",
      backdrop: "grid",
      accent: "primary",
      // The hook carries the whole video. The read counter climbing 1, 3, 6, 10,
      // 15... while the row barely grows is the argument, made before a single
      // word of explanation.
      visual: "rescan",
      rescan: { cached: false, tokens: 14 },
      camera: { distance: 11.5, yaw: -0.3, pitch: 0.12 },
      subjectState: 0,
    },
    {
      id: "scribe-problem",
      start: 11,
      duration: 12,
      headline: "Except this scribe re-reads the *entire manuscript* before every single word.",
      body: "Word one: read one word. Word two: read two. Word ten thousand: re-read all 9,999 before writing one more.",
      backdrop: "grid",
      accent: "secondary",
      camera: { distance: 8.2, yaw: 0.34, pitch: -0.05 },
      subjectState: 0,
    },
    {
      id: "cold-open-turn",
      start: 23,
      duration: 11,
      headline: "Nobody works this way.\nAnd yet, without one trick, *this is exactly how an LLM would generate text*.",
      backdrop: "grid",
      accent: "secondary",
      camera: { distance: 11.8, yaw: 0.05, pitch: 0.26 },
      subjectState: 0,
    },
    {
      id: "roadmap",
      start: 34,
      duration: 16,
      kicker: "WHAT YOU'LL GET",
      headline: "Six things, in order.",
      backdrop: "grid",
      accent: "primary",
      visual: "bullets",
      bullets: [
        { title: "What an LLM does", sub: "When it reads and writes text" },
        { title: "What the KV cache is", sub: "Plainly first, then precisely" },
        { title: "Why switching models re-reads", sub: "The full prefill cost" },
        { title: "Why two models can't share", sub: "Structural and semantic" },
        { title: "The engineering toolbox", sub: "MQA, GQA, MLA, paging, quantisation" },
        { title: "What sharing would take", sub: "And why it is never free" },
      ],
      camera: { distance: 12.5, yaw: -0.5, pitch: 0.14 },
      subjectState: 0.05,
    },

    // ---------------------------------------------------------------- PART 1
    {
      id: "basics-kicker",
      start: 50,
      duration: 10,
      kicker: "PART 1 · THE BASICS",
      headline: "An LLM doesn't understand words. It understands *numbers*.",
      backdrop: "rays",
      accent: "primary",
      visual: "tokenize",
      tokenize: { word: "unbelievable", pieces: ["un", "believ", "able"] },
      camera: { distance: 11.2, yaw: 0.4, pitch: 0.08 },
      subjectState: 0.08,
    },
    {
      id: "tokens",
      start: 60,
      duration: 12,
      headline: "Every word-piece, every *token*, becomes a long list of numbers.",
      body: "And the model's job, at every single step, is the same: given all the tokens so far, predict the next one.",
      backdrop: "rays",
      accent: "primary",
      camera: { distance: 8.6, yaw: -0.42, pitch: 0.18 },
      subjectState: 0.1,
    },
    {
      id: "prediction-game",
      start: 72,
      duration: 13,
      headline: "You don't need a dictionary to finish this. You need *context*.",
      backdrop: "rays",
      accent: "primary",
      visual: "predict",
      predict: {
        prompt: "The chef added a pinch of ___",
        candidates: [
          { label: "salt", p: 0.62 },
          { label: "pepper", p: 0.19 },
          { label: "sugar", p: 0.08 },
          { label: "cement", p: 0.002, absurd: true },
        ],
      },
      camera: { distance: 12.6, yaw: 0.12, pitch: 0.3 },
      subjectState: 0.12,
    },
    {
      id: "attention-named",
      start: 85,
      duration: 11,
      headline: "The model asks every previous token: *how relevant are you to what comes next?*",
      body: "That relevance-scoring mechanism is called attention. It is the heart of the transformer.",
      backdrop: "rays",
      accent: "primary",
      camera: { distance: 9.1, yaw: -0.2, pitch: -0.04 },
      subjectState: 0.14,
    },

    // ---------------------------------------------------------------- PART 2
    {
      id: "kitchen-kicker",
      start: 96,
      duration: 10,
      kicker: "PART 2 · ATTENTION",
      headline: "Picture a professional kitchen during dinner service.",
      backdrop: "rays",
      accent: "primary",
      camera: { distance: 10.4, yaw: 0.52, pitch: 0.2 },
      subjectState: 0.16,
    },
    {
      id: "qkv-intro",
      start: 106,
      duration: 11,
      headline: "Every dish being cooked needs to know which ingredients on the counter matter to it.",
      body: "To settle that, each token produces three things.",
      backdrop: "rays",
      accent: "primary",
      camera: { distance: 8.9, yaw: -0.3, pitch: 0.1 },
      subjectState: 0.18,
    },
    {
      id: "qkv-chips",
      start: 117,
      duration: 18,
      kicker: "QUERY · KEY · VALUE",
      headline: "Three signs, held up at once.",
      backdrop: "rays",
      accent: "primary",
      visual: "chips",
      chips: [
        { label: "Query", sub: "what am I after?", color: "#6FD5FF" },
        { label: "Key", sub: "what do I offer?", color: "#FFB86B" },
        { label: "Value", sub: "my actual substance", color: "#A78BFA" },
      ],
      camera: { distance: 12.8, yaw: 0.16, pitch: 0.22 },
      subjectState: 0.2,
    },
    {
      id: "qkv-explained",
      start: 135,
      duration: 15,
      headline: "The dish holds up *\"I need something acidic\"*. The lemon holds up *\"I am acidic\"*.",
      body: "Compare your Query against everyone's Key, see who matches, then pull in their Value weighted by how good the match was. That is attention, in one sentence.",
      backdrop: "rays",
      accent: "primary",
      camera: { distance: 9.3, yaw: -0.46, pitch: 0.06 },
      subjectState: 0.22,
    },
    {
      id: "every-layer",
      start: 150,
      duration: 12,
      headline: "Every token does this. At every layer. On every step.",
      body: "Models have dozens of layers, each refining the representation further. That is a lot of matching.",
      backdrop: "beams",
      accent: "secondary",
      camera: { distance: 13.4, yaw: 0.3, pitch: -0.1 },
      subjectState: 0.24,
    },

    // ---------------------------------------------------------------- PART 3
    {
      id: "naive-kicker",
      start: 162,
      duration: 11,
      kicker: "PART 3 · THE NAIVE WAY",
      headline: "Now here is where it gets *expensive*.",
      backdrop: "grid",
      accent: "secondary",
      camera: { distance: 8.4, yaw: -0.36, pitch: 0.02 },
      subjectState: 0.2,
      wash: true,
    },
    {
      id: "autoregressive",
      start: 173,
      duration: 13,
      headline: "Text comes out one token at a time. *Autoregressive* generation.",
      body: "Each new token is appended, and the model produces the next by looking at the whole sequence again, including the token it just wrote.",
      backdrop: "grid",
      accent: "secondary",
      camera: { distance: 9.6, yaw: 0.44, pitch: 0.16 },
      subjectState: 0.18,
    },
    {
      id: "reintroduce",
      start: 186,
      duration: 14,
      headline: "Every ingredient re-introduces itself to every dish. From scratch. Every time.",
      body: "Recalculating every Key and Value from raw ingredients, on every single step of generation.",
      backdrop: "grid",
      accent: "secondary",
      camera: { distance: 8.0, yaw: -0.2, pitch: -0.12 },
      subjectState: 0.15,
    },
    {
      id: "naive-cost",
      start: 200,
      duration: 16,
      kicker: "THE COST",
      headline: "The work per step keeps growing.",
      backdrop: "grid",
      accent: "secondary",
      visual: "formula",
      formula: {
        lines: [
          "token     1  →  compute K,V for 1 token",
          "token     2  →  recompute K,V for tokens 1–2",
          "token     3  →  recompute K,V for tokens 1–3",
          "     ...",
          "token 10000  →  recompute K,V for tokens 1–10000",
        ],
        highlight: [4],
        caption: "O(n) work at every one of n steps. Quadratic total, before attention itself is counted.",
      },
      camera: { distance: 14.2, yaw: 0.1, pitch: 0.08 },
      subjectState: 0.12,
    },
    {
      id: "the-waste",
      start: 216,
      duration: 15,
      headline: "But the Key and Value for token 47 *don't change* because token 9,999 showed up.",
      body: "Token 47 said its piece already. Its sign and its substance are fixed forever, determined by itself and everything before it, never by what comes after.",
      backdrop: "grid",
      accent: "primary",
      camera: { distance: 8.8, yaw: -0.5, pitch: 0.2 },
      subjectState: 0.14,
    },

    // ---------------------------------------------------------------- PART 4
    {
      id: "fix-kicker",
      start: 231,
      duration: 11,
      kicker: "PART 4 · THE FIX",
      headline: "The fix is almost embarrassingly simple once you see it.",
      backdrop: "rings",
      accent: "primary",
      camera: { distance: 10.8, yaw: 0.2, pitch: 0.24 },
      subjectState: 0.2,
      wash: true,
    },
    {
      id: "write-it-down",
      start: 242,
      duration: 12,
      headline: "Write down each ingredient's Key and Value the first time. *Never recompute them.*",
      backdrop: "rings",
      accent: "primary",
      camera: { distance: 8.3, yaw: -0.28, pitch: 0.05 },
      subjectState: 0.45,
      wash: true,
    },
    {
      id: "index-cards",
      start: 254,
      duration: 14,
      headline: "A shelf of index cards. One per ingredient.",
      body: "Each card lists what I am (the Key) and what I bring to the dish (the Value). New dishes just walk the shelf and read.",
      backdrop: "rings",
      accent: "primary",
      camera: { distance: 9.9, yaw: 0.38, pitch: -0.02 },
      subjectState: 0.62,
      wash: true,
    },
    {
      id: "this-is-it",
      start: 268,
      duration: 9,
      headline: "That shelf is the *KV cache*.",
      backdrop: "rings",
      accent: "primary",
      camera: { distance: 7.6, yaw: 0.0, pitch: 0.0 },
      subjectState: 0.78,
      wash: true,
    },
    {
      id: "formally",
      start: 277,
      duration: 17,
      kicker: "PRECISELY",
      headline: "A stored tensor, at every layer, for every head.",
      backdrop: "rings",
      accent: "primary",
      visual: "formula",
      formula: {
        lines: [
          "on each new token:",
          "  1.  compute Q, K, V  ->  for that token only",
          "  2.  append K, V      → cache",
          "  3.  attend Q over all cached K, V",
        ],
        highlight: [1],
        caption: "Holding the Key and Value vectors of every token processed so far.",
      },
      camera: { distance: 13.8, yaw: -0.16, pitch: 0.1 },
      subjectState: 0.85,
    },
    {
      id: "cost-collapse",
      start: 294,
      duration: 13,
      headline: "Quadratic work collapses to *roughly constant* per token.",
      backdrop: "rings",
      accent: "primary",
      // Deliberately the same component as the cold open, with cached: true.
      // Identical layout, opposite behaviour — the counter now climbs by one.
      visual: "rescan",
      rescan: { cached: true, tokens: 14 },
      camera: { distance: 11.8, yaw: 0.46, pitch: 0.18 },
      subjectState: 0.9,
    },
    {
      id: "ttft",
      start: 307,
      duration: 15,
      kicker: "WHY THE FIRST TOKEN IS SLOW",
      headline: "The model builds the *entire* cache for your prompt before it writes anything.",
      body: "That is time-to-first-token. Every token after streams fast. It is just one more card on an already-built shelf.",
      backdrop: "rings",
      accent: "secondary",
      camera: { distance: 10.6, yaw: -0.4, pitch: -0.08 },
      subjectState: 0.92,
    },

    // ---------------------------------------------------------------- PART 5
    {
      id: "memory-kicker",
      start: 322,
      duration: 11,
      kicker: "PART 5 · IN MEMORY",
      headline: "It isn't one shelf. It's one shelf *per layer, per head*.",
      backdrop: "beams",
      accent: "primary",
      camera: { distance: 14.6, yaw: 0.24, pitch: 0.3 },
      subjectState: 0.95,
    },
    {
      id: "skyscraper",
      start: 333,
      duration: 13,
      headline: "A skyscraper of kitchens, stacked floor on floor.",
      body: "Each floor a layer. Each station on it a head.",
      visual: "layers",
      layers: { count: 6, bottomLabel: "input", topLabel: "output" },
      backdrop: "beams",
      accent: "primary",
      camera: { distance: 12.2, yaw: -0.55, pitch: -0.16 },
      subjectState: 1,
    },
    {
      id: "cache-size",
      start: 346,
      duration: 17,
      kicker: "ROUGHLY",
      headline: "What that costs you.",
      backdrop: "beams",
      accent: "secondary",
      visual: "formula",
      formula: {
        lines: [
          "cache size  ≈  layers",
          "             × heads",
          "             × head_dim",
          "             × sequence_length",
          "             × 2            (one for K, one for V)",
          "             × bytes_per_number",
        ],
        highlight: [3],
        caption: "Sequence length is the term that grows while you talk, which is why long conversations eat GPU memory.",
      },
      camera: { distance: 14.0, yaw: 0.08, pitch: 0.12 },
      subjectState: 1,
    },
    {
      id: "different-models-differ",
      start: 363,
      duration: 12,
      headline: "Two models hold *wildly different* cache sizes for the exact same conversation.",
      body: "Different numbers of floors, different numbers of stations. Remember that. It matters in ninety seconds.",
      backdrop: "beams",
      accent: "secondary",
      camera: { distance: 9.4, yaw: -0.3, pitch: 0.06 },
      subjectState: 1,
    },

    // ---------------------------------------------------------------- PART 6
    {
      id: "switch-kicker",
      start: 375,
      duration: 12,
      kicker: "PART 6 · SWITCHING MODELS",
      headline: "The cache is *not* the conversation.",
      backdrop: "grid",
      accent: "secondary",
      camera: { distance: 8.1, yaw: 0.36, pitch: -0.05 },
      subjectState: 1,
    },
    {
      id: "private-notes",
      start: 387,
      duration: 14,
      headline: "It is one model's private, internal notes about the conversation, in its own shorthand.",
      body: "Written by weight matrices learned during that model's own training. Nobody else's.",
      backdrop: "grid",
      accent: "secondary",
      camera: { distance: 10.2, yaw: -0.44, pitch: 0.2 },
      subjectState: 1,
    },
    {
      id: "two-chefs",
      start: 401,
      duration: 13,
      headline: "Two master chefs. Two kitchens. Two *personally trained* senses of taste.",
      body: "Chef Sonnet tastes a lemon and writes: sharp-6, pairs well with fatty-9. Those numbers are Sonnet's own rating system.",
      backdrop: "grid",
      accent: "secondary",
      camera: { distance: 11.6, yaw: 0.5, pitch: 0.1 },
      subjectState: 1,
    },
    {
      id: "opus-reads",
      start: 414,
      duration: 11,
      headline: "Now ask Chef Opus to take over mid-dish and read those cards.",
      body: "Opus has no idea what it means. Four separate reasons why.",
      visual: "mismatch",
      mismatch: {
        left: { label: "Sonnet", rows: 6 },
        right: { label: "Opus", rows: 9 },
        note: "no floor-to-floor mapping exists",
      },
      backdrop: "grid",
      accent: "secondary",
      camera: { distance: 8.7, yaw: -0.18, pitch: -0.14 },
      subjectState: 1,
    },
    {
      id: "four-reasons",
      start: 425,
      duration: 22,
      kicker: "WHY IT'S MEANINGLESS",
      headline: "Not inaccurate. *Meaningless*.",
      backdrop: "grid",
      accent: "secondary",
      visual: "bullets",
      bullets: [
        { title: "Different weights", sub: "A 6 on Sonnet's scale is not a 6 on Opus's. They measure incompatible things" },
        { title: "Different architecture", sub: "Other layer counts, heads, head dimensions. It may not even fit" },
        { title: "Cascading dependency", sub: "Floor 12's cards were written from floor 11's output, all the way down" },
        { title: "Different tokenizers", sub: "They may not even slice the text into the same pieces" },
      ],
      camera: { distance: 13.2, yaw: 0.28, pitch: 0.16 },
      subjectState: 1,
    },
    {
      id: "not-translation",
      start: 447,
      duration: 13,
      headline: "This isn't a translation problem. It's a *different language*, written in numbers.",
      body: "Numbers that only mean anything inside one specific chef's head.",
      backdrop: "grid",
      accent: "secondary",
      camera: { distance: 9.0, yaw: -0.5, pitch: 0.04 },
      subjectState: 1,
    },
    {
      id: "the-only-fix",
      start: 460,
      duration: 15,
      headline: "The only fix: hand the new chef the raw transcript and let them build their *own* shelf.",
      body: "That is the full re-read you see in Claude Code when you switch models. The old cache is thrown away and a fresh prefill runs your whole history through the new model.",
      backdrop: "rings",
      accent: "primary",
      camera: { distance: 10.9, yaw: 0.14, pitch: 0.22 },
      subjectState: 0.15,
      wash: true,
    },
    {
      id: "why-slow",
      start: 475,
      duration: 11,
      headline: "Which is why the first reply after a switch takes noticeably longer.",
      body: "You are paying the read-the-whole-manuscript cost all over again, for the new chef.",
      backdrop: "rings",
      accent: "secondary",
      camera: { distance: 8.5, yaw: -0.34, pitch: -0.06 },
      subjectState: 0.4,
      wash: true,
    },

    // ---------------------------------------------------------------- PART 7
    {
      id: "share-kicker",
      start: 486,
      duration: 12,
      kicker: "PART 7 · SHARING",
      headline: "Different question: could two models read the same shelf *right now*?",
      body: "Short answer: only if they were built to be the same chef in the parts that matter.",
      backdrop: "grid",
      accent: "secondary",
      camera: { distance: 11.4, yaw: 0.42, pitch: 0.18 },
      subjectState: 0.6,
    },
    {
      id: "two-compatibilities",
      start: 498,
      duration: 20,
      kicker: "WHAT IT WOULD TAKE",
      headline: "Two kinds of compatibility. You need *both*.",
      backdrop: "grid",
      accent: "secondary",
      visual: "compare",
      compare: {
        left: {
          title: "A · Structural",
          points: [
            "Same number of layers",
            "Same heads per layer",
            "Same head dimension",
            "Same tokenizer",
            "80 floors vs 60 has no sane mapping",
          ],
        },
        right: {
          title: "B · Semantic",
          points: [
            "The numbers on the cards must mean the same thing",
            "Requires W_K and W_V identical or deliberately aligned",
            "Training is non-linear and high-dimensional",
            "Two separately trained models never land there",
          ],
        },
      },
      camera: { distance: 14.4, yaw: -0.12, pitch: 0.1 },
      subjectState: 0.6,
    },
    {
      id: "twins",
      start: 518,
      duration: 14,
      headline: "Twins raised apart, each inventing their own private shorthand.",
      body: "Both notations are equally good. Twin A's notes are still gibberish to twin B. Not because either is wrong, but because compatibility was never a design goal.",
      backdrop: "grid",
      accent: "secondary",
      camera: { distance: 9.7, yaw: 0.3, pitch: -0.1 },
      subjectState: 0.6,
    },

    // ---------------------------------------------------------------- PART 8
    {
      id: "toolbox-kicker",
      start: 532,
      duration: 11,
      kicker: "PART 8 · THE TOOLBOX",
      headline: "From clever trick to an entire subfield of systems engineering.",
      backdrop: "rings",
      accent: "primary",
      camera: { distance: 13.0, yaw: -0.4, pitch: 0.26 },
      subjectState: 0.75,
      wash: true,
    },
    {
      id: "shrink-per-token",
      start: 543,
      duration: 20,
      kicker: "8.1 · SHRINK PER TOKEN",
      headline: "Share the spice rack.",
      backdrop: "rings",
      accent: "primary",
      visual: "bullets",
      bullets: [
        { title: "MQA", sub: "One shared K/V shelf for all heads. Big saving, small quality cost" },
        { title: "GQA", sub: "Groups of heads share a shelf. Used in Llama 3 and Mistral. The middle ground" },
        { title: "MLA", sub: "Store a compressed latent, reconstruct K/V on demand. DeepSeek-V2/V3" },
      ],
      camera: { distance: 12.6, yaw: 0.34, pitch: 0.12 },
      subjectState: 0.8,
    },
    {
      id: "shrink-by-forgetting",
      start: 563,
      duration: 21,
      kicker: "8.2 · SHRINK BY FORGETTING",
      headline: "Throw cards away, carefully.",
      backdrop: "rings",
      accent: "secondary",
      visual: "bullets",
      bullets: [
        { title: "Sliding window", sub: "Discard anything older than N tokens. Fast, but it cannot look further back" },
        { title: "Attention sinks", sub: "The first few tokens are load-bearing anchors. Keep those, plus a recent window" },
        { title: "H2O eviction", sub: "Track which cards actually get attended to, evict the ones nobody reads" },
      ],
      camera: { distance: 12.9, yaw: -0.26, pitch: -0.08 },
      subjectState: 0.55,
      wash: true,
    },
    {
      id: "server-side",
      start: 584,
      duration: 18,
      kicker: "8.3 · IN THE SERVER",
      headline: "Stop reserving a banquet hall for a table of one.",
      backdrop: "beams",
      accent: "primary",
      visual: "bullets",
      bullets: [
        { title: "PagedAttention", sub: "Hand out shelf space in pages, like an OS. vLLM. Kills fragmentation waste" },
        { title: "Quantisation", sub: "Write the cards in int8 or int4, not 16-bit floats. Smaller, faster, tiny cost" },
      ],
      camera: { distance: 11.8, yaw: 0.48, pitch: 0.2 },
      subjectState: 0.85,
      wash: true,
    },
    {
      id: "prefix-caching",
      start: 602,
      duration: 15,
      kicker: "8.4 · REUSE ACROSS REQUESTS",
      headline: "*Prefix caching*. Don't re-cook the starter you already prepped.",
      body: "Two requests to the same model sharing an identical prefix (a long system prompt, the head of a conversation) can reuse the computed cache instead of rebuilding it.",
      backdrop: "beams",
      accent: "primary",
      camera: { distance: 9.3, yaw: -0.2, pitch: 0.08 },
      subjectState: 1,
      wash: true,
    },
    {
      id: "the-fine-print",
      start: 617,
      duration: 17,
      kicker: "THE FINE PRINT",
      headline: "Same model. *Exact* token-for-token prefix match.",
      body: "Change anything upstream, including which model you are on, and the match breaks, the cache is invalidated, and you are back to a full prefill. That is the mechanism behind the behaviour you noticed.",
      backdrop: "beams",
      accent: "secondary",
      camera: { distance: 10.5, yaw: 0.4, pitch: -0.12 },
      subjectState: 0.2,
      wash: true,
    },

    // ---------------------------------------------------------------- PART 9
    {
      id: "what-would-it-take",
      start: 634,
      duration: 12,
      kicker: "PART 9 · WHAT WOULD IT TAKE",
      headline: "Nobody does this in production between two independently trained models.",
      body: "But research points at four routes.",
      backdrop: "rays",
      accent: "primary",
      camera: { distance: 12.4, yaw: -0.46, pitch: 0.24 },
      subjectState: 0.5,
      wash: true,
    },
    {
      id: "four-routes",
      start: 646,
      duration: 24,
      kicker: "FOUR ROUTES",
      headline: "None of them are free.",
      backdrop: "rays",
      accent: "primary",
      visual: "bullets",
      bullets: [
        { title: "Shared frozen trunk", sub: "One backbone, different heads. Early-layer cache is genuinely shareable" },
        { title: "Representation alignment", sub: "Distil with a loss forcing intermediate layers to stay numerically aligned" },
        { title: "Speculative decoding", sub: "The real-world one, and notably they do NOT share a cache" },
        { title: "A translation adapter", sub: "Train a net to map model A's K/V to model B's. Speculative, not in production" },
      ],
      camera: { distance: 13.6, yaw: 0.2, pitch: 0.14 },
      subjectState: 0.5,
    },
    {
      id: "spec-decoding",
      start: 670,
      duration: 16,
      kicker: "WHY SPECULATIVE DECODING WORKS",
      headline: "It shares *tokens*, not tensors.",
      body: "A small draft model proposes ahead; the big model verifies in one batched pass. Each keeps its own cache in its own format. Plain token IDs carry no model-specific internal meaning, so they are safe to pass between architectures.",
      backdrop: "rays",
      accent: "primary",
      camera: { distance: 9.8, yaw: -0.36, pitch: 0.0 },
      subjectState: 0.7,
      wash: true,
    },
    {
      id: "the-throughline",
      start: 686,
      duration: 17,
      kicker: "THE THROUGHLINE",
      headline: "You can never share the cache for free.",
      backdrop: "rays",
      accent: "secondary",
      visual: "formula",
      formula: {
        lines: [
          "either  →  force the models to be identical where it counts",
          "    or  →  pay an explicit translation cost",
          "    or  →  share something cache-agnostic instead  (tokens)",
        ],
        highlight: [2],
        caption: "Every real technique is one of these three. There is no fourth option.",
      },
      camera: { distance: 14.2, yaw: 0.1, pitch: 0.1 },
      subjectState: 0.7,
    },

    // --------------------------------------------------------------- PART 10
    {
      id: "summary",
      start: 703,
      duration: 18,
      kicker: "IN ONE PARAGRAPH",
      headline: "A running notebook of every token's *identity card* and *substance*.",
      body: "Saved so the model never recomputes a token's contribution twice, turning painfully quadratic generation into roughly linear generation.",
      backdrop: "deep",
      accent: "primary",
      camera: { distance: 10.2, yaw: -0.24, pitch: 0.18 },
      subjectState: 1,
      wash: true,
    },
    {
      id: "summary-two",
      start: 721,
      duration: 15,
      headline: "But that notebook is written in *one model's private shorthand*.",
      body: "Shaped by its exact architecture and trained weights. It cannot be handed to another model without being rebuilt from scratch, or the two being engineered from the ground up to think alike.",
      backdrop: "deep",
      accent: "secondary",
      camera: { distance: 8.9, yaw: 0.44, pitch: -0.08 },
      subjectState: 1,
    },
    {
      id: "endcard",
      start: 736,
      duration: 8,
      headline: "*Cache the work.*\n~Never~ the understanding.",
      backdrop: "deep",
      accent: "primary",
      visual: "endcard",
      camera: { distance: 13.4, yaw: 0.04, pitch: 0.3 },
      subjectScreen: { x: 0.5, y: 0.33 },
      subjectState: 1,
    },
  ],
};
